- name: Write configs for user packages
  hosts: all
  gather_facts: true

  tasks:
  - name: Ensure Alacritty config directory exists
    file:
      path: "{{ ansible_env.HOME }}/.config/alacritty"
      state: directory
      mode: '0755'

  - name: write alacritty config
    template:
      src: templates/alacritty/alacritty.toml.j2
      dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
      mode: '0644'

  - name: Ensure nvim config directory exists
    file:
      path: "{{ ansible_env.HOME }}/.config/nvim"
      state: directory
      mode: '0755'

  - name: Deploy NeoVim Config
    synchronize:
      src: templates/nvim/
      dest: "{{ ansible_env.HOME }}/.config/nvim"
      recursive: yes
      mode: push

  - name: Deploy Tmux Config
    template:
      src: templates/tmux/tmux.conf.j2
      dest: "{{ ansible_env.HOME }}/.config/.tmux.conf"
      mode: '0644'
