- name: Install ppa pkgs
  hosts: all
  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False

  tasks:
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - clangd-14
          - git
          - cmake 
          - g++ 
          - pkg-config 
          - libfreetype6-dev 
          - libfontconfig1-dev 
          - libxcb-xfixes0-dev 
          - libxkbcommon-dev 
          - python3
          - htop
          - nvtop
          - nmap
