- name: Install diesel
  hosts: all
  gather_facts: true
  become: true

  tasks:

  - name: uri
    uri:
      url: https://github.com/diesel-rs/diesel/releases/latest/download/diesel_cli-installer.sh
      dest: /tmp/
      mode: 0777

  - name: execute script
    command:
      cmd: sh /tmp/diesel_cli-installer.sh
