- name: install
  hosts: all
  become: true
  tasks:
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - clangd-14
          - cmake 
          - g++ 
          - pkg-config 
          - libfreetype6-dev 
          - libfontconfig1-dev 
          - libxcb-xfixes0-dev 
          - libxkbcommon-dev 
          - python3
          - tmux
